### ISSUE TITLE
githubユーザ名が取得されない

### ISSUE THREAD

**Issue by inomata137** [AtelierArith/OkinawaCompPhysFoodSurvey2024.jl#20]
```sh
# inomata137 @ Kronos in ~/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl on git:inomata137/okinawa-food x [9:32:48] 
$ git config --get github.user
inomata137

# inomata137 @ Kronos in ~/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl on git:inomata137/okinawa-food x [9:33:08] 
$ julia --project interactive.jl 
[ Info: githubuser=
ERROR: LoadError: Git hosting service username is required, set one with keyword `githubuser="<YourGitHubUserName>"`
Stacktrace:
 [1] interactive(; githubuser::Nothing)
   @ Main ~/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl/interactive.jl:20
 [2] interactive()
   @ Main ~/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl/interactive.jl:15
 [3] top-level scope
   @ ~/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl/interactive.jl:49
in expression starting at /Users/inomata137/Desktop/projects/OkinawaCompPhysFoodSurvey2024.jl/interactive.jl:49

```

## 環境
- MacBook Pro(M3 Pro)
- julia version 1.10.2

**Comment by terasakisatoshi** [comment]
こちらをご確認ください

https://github.com/AtelierArith/OkinawaCompPhysFoodSurvey2024.jl/issues/6#issuecomment-1982183452

**Comment by inomata137** [comment]
```
$ git config --get github.user
inomata137
```
となるので、git側の設定はできているはずだと思います

**Comment by saintbenjamin** [comment]
GitHub Desktopのご使用をも検討していただけますかね。GUI環境なのでかなり楽です。僕はGitLabの方はCLIで楽にやってますが、GitHubの方はちょっとCLIだと不具合があって、GitHub Desktopでやっちゃってます。

**Comment by toririm** [comment]
私の環境でもこのIssueと同様の状態が再現しました。

`.git/config`に
```toml
[github]
	user = toririm
```
が含まれていても、動作しませんでした。

### 環境
- Windows 11
- Julia Version 1.10.2

**Comment by saintbenjamin** [comment]
GitHub Desktopを事前にいれとけば、gitのRPMが全然入ってなかったのにも関わらず、普通にjuliaがGitHubとつながってました。

https://linux.how2shout.com/how-to-install-github-desktop-on-latest-fedora-linux/

**Comment by saintbenjamin** [comment]
僕はWindows 11上で、WSL2を回していて、MS StoreにないFedora 38を無理やりWSL2にインストールして使っています。GitはFedoraの中で使ってます。

**Comment by toririm** [comment]
`git config --global github.user <username>`
に置き換えて実行した場合、手順通りに動作しました。

どうやらLibGit2がデフォルトで読んでいるgitconfigはグローバルのもののようです。
