### ISSUE TITLE
interactive.jlでテンプレートが作成できない

### ISSUE THREAD

**Issue by higa56** [AtelierArith/OkinawaCompPhysFoodSurvey2024.jl#72]
$ julia --project interactive.jl
に対して
$ LoadError: Git hosting service username is required, set one with keyword `githubuser="<YourGitHubUserName>"`
というエラーが出ます．

**Comment by toririm** [comment]
[#6 ](https://github.com/AtelierArith/OkinawaCompPhysFoodSurvey2024.jl/issues/6#issuecomment-1982183452)
の手順で`git config ...`の操作は行っていますでしょうか？

行っている場合は、Fork Syncとgit pullを行ったうえで再度試してみてください

**Comment by higa56** [comment]
$ git config --global github.user <username>
を打ち込んで解決できました．
